### Hey 👋

#### 👷 My recent pull requests
{{range recentPullRequests 20}}
- ![](./assets/pr-{{ .State | toLower }}.svg) [{{.Title}}]({{.URL}}) on [{{.Repo.Name}}]({{.Repo.URL}}) ({{humanize .CreatedAt}})
{{- end}}

#### 📜 My recent blog posts (https://hugo.alliau.me/blog)
{{range rss "https://hugo.alliau.me/blog/rss.xml" 8}}
- [{{.Title}}]({{.URL}}) ({{humanize .PublishedAt}})
{{- end}}

#### 📫 How to reach me

- Twitter/X: https://twitter.com/HugoAlliaume
- Website: https://hugo.alliau.me

---

_This README has been generated by [readme-scribe](https://github.com/muesli/readme-scribe/)_.

